upstream_project_url: https://github.com/fedora-iot/greenboot

specfile_path: greenboot.spec
files_to_sync:
  - greenboot.spec
  - .packit.yaml
upstream_package_name: greenboot
upstream_tag_template: v{version}
downstream_package_name: greenboot

packages:
  greenboot-fedora:
    downstream_package_name: greenboot
    upstream_package_name: greenboot
  greenboot-centos:
    downstream_package_name: greenboot
    upstream_package_name: greenboot
    pkg_tool: centpkg

jobs:

  # Fedora jobs

  - &greenboot_copr_build_fedora
    job: copr_build
    packages: [greenboot-fedora]
    trigger: pull_request
    targets: ["fedora-latest-stable", "fedora-latest", "fedora-rawhide"]

  - <<: *greenboot_copr_build_fedora
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot

  - job: sync_from_downstream
    trigger: commit

  - job: propose_downstream
    trigger: release
    packages: [greenboot-fedora]
    dist_git_branches: ["fedora-development", "fedora-latest-stable"]

  - job: koji_build
    trigger: commit
    allowed_pr_authors: [all_committers]
    dist_git_branches: ["fedora-development", "fedora-latest-stable"]

  - job: bodhi_update
    trigger: commit
    allowed_builders: [all_committers]
    dist_git_branches: ["fedora-development", "fedora-latest-stable"]

  # CentOS jobs

  - &greenboot_copr_build_centos
    job: copr_build
    packages: [greenboot-centos]
    trigger: pull_request
    targets: ["centos-stream-9", "centos-stream-10"]

  - <<: *greenboot_copr_build_centos
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot
