specfile_path: greenboot.spec
synced_files:
  - greenboot.spec
  - .packit.yaml
upstream_package_name: greenboot
upstream_tag_template: v{version}
downstream_package_name: greenboot
jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
