# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/28-cloud-base"

  config.vm.provision "shell", inline: <<-SHELL
    curl https://copr.fedorainfracloud.org/coprs/lorbus/greenboot/repo/fedora-28/lorbus-greenboot-fedora-28.repo --output /etc/yum.repos.d/_copr_lorbus-greenboot.repo
    dnf install -y greenboot greenboot-notifications
    # mv /vagrant/10_failing_check.sh /etc/greenboot.d/check/required/10_failing_check.sh
    systemctl enable greenboot.target
    systemctl start greenboot.target
    sleep 5
    journalctl -u greenboot.target
    journalctl -u greenboot
    journalctl -t greenboot.sh
  SHELL

end
