#!/bin/bash
set -eo pipefail

source /usr/libexec/greenboot/greenboot-boot-remount

# Run the grub2-editenv commands
/usr/bin/grub2-editenv /boot/grub2/grubenv set boot_success=1

/usr/bin/grub2-editenv /boot/grub2/grubenv unset boot_counter
